Repository CS2103JAN2018-F14-B1/main, pull requests merged in 2018-04, with the labels that each got.

#104 v1.4 add event handlers for tag colour, view team and create new team
  src/main/java/seedu/address/commons/events/ui/ChangeTagColourEvent.java
  src/main/java/seedu/address/commons/events/ui/DeselectTeamEvent.java
  src/main/java/seedu/address/commons/events/ui/HighlightSelectedTeamEvent.java
  src/main/java/seedu/address/commons/events/ui/ShowNewTeamNameEvent.java
  src/main/java/seedu/address/logic/commands/CreateCommand.java
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/logic/commands/SetCommand.java
  src/main/java/seedu/address/logic/commands/ViewCommand.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/java/seedu/address/ui/TeamDisplay.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/MainWindow.fxml
  src/test/java/seedu/address/ui/TeamDisplayTest.java
Labels: status.readyForReview, status.readyToMerge, type.enhancement, v1.4

#110 UserGuide: Update and format
  docs/UserGuide.adoc
Labels: file.userGuide

#113 Toggle Privacy for fields
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/TogglePrivacyCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/TogglePrivacyCommandParser.java
  src/main/java/seedu/address/model/person/Address.java
  src/main/java/seedu/address/model/person/Email.java
  src/main/java/seedu/address/model/person/Name.java
  src/main/java/seedu/address/model/person/Phone.java
  src/main/java/seedu/address/model/person/Rating.java
  src/main/java/seedu/address/model/person/Remark.java
  src/main/java/seedu/address/storage/XmlAdaptedPerson.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/java/seedu/address/ui/PlayerDetails.java
  src/test/java/seedu/address/testutil/EditPersonPrivacyBuilder.java
Labels: status.ongoing

#112 DevGuide: Update for v1.4
  docs/DeveloperGuide.adoc
Labels: file.devGuide, status.ongoing

#111 AboutUs: Update with latest feature contribution
  docs/AboutUs.adoc
Labels: status.readyToMerge

#109 ReadMe: Add logo of MTM
  README.adoc
  docs/images/MyTeamManagerLogo.png
Labels: status.readyToMerge

#114 Updated sort command to include fields
  src/main/java/seedu/address/logic/commands/SortCommand.java
  src/main/java/seedu/address/logic/parser/SortCommandParser.java
  src/main/java/seedu/address/model/person/UniquePersonList.java
  src/test/java/seedu/address/logic/commands/SortCommandTest.java
Labels: status.readyToMerge, type.enhancement

#116 v1.4 player details panel
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/java/seedu/address/ui/PlayerDetails.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/PersonListCard.fxml
  src/main/resources/view/PlayerDetails.fxml
  src/test/java/guitests/guihandles/PersonCardHandle.java
  src/test/java/seedu/address/ui/testutil/GuiTestAssert.java
  src/test/java/systemtests/AddCommandSystemTest.java
  src/test/java/systemtests/EditCommandSystemTest.java
Labels: priority.high, status.readyForReview, status.readyToMerge, type.enhancement

#115 V1.4 collation of code
  Collate-TUI.jar
  collated/functional/Codee.md
  collated/test/Codee.md
  src/main/java/seedu/address/commons/events/ui/ChangeTagColourEvent.java
  src/main/java/seedu/address/commons/events/ui/HighlightSelectedTeamEvent.java
  src/main/java/seedu/address/commons/events/ui/ShowNewTeamNameEvent.java
  src/main/java/seedu/address/logic/commands/SetCommand.java
  src/main/java/seedu/address/logic/parser/SetCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/tag/Tag.java
  src/main/java/seedu/address/storage/XmlAdaptedTag.java
  src/main/java/seedu/address/storage/XmlAdaptedTeam.java
  src/main/java/seedu/address/storage/XmlSerializableAddressBook.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/java/seedu/address/ui/PlayerDetails.java
  src/main/java/seedu/address/ui/TeamDisplay.java
  src/main/resources/view/PlayerDetails.fxml
  src/main/resources/view/TeamDisplay.fxml
  src/test/java/guitests/guihandles/TeamDisplayHandle.java
  src/test/java/seedu/address/logic/commands/SetCommandTest.java
  src/test/java/seedu/address/logic/parser/RemarkCommandParserTest.java
  src/test/java/seedu/address/logic/parser/SetCommandParserTest.java
  src/test/java/seedu/address/testutil/TeamBuilder.java
  src/test/java/seedu/address/testutil/TypicalTags.java
  src/test/java/seedu/address/ui/TeamDisplayTest.java
Labels: status.readyForReview, status.readyToMerge, type.task, v1.4

#118 1.4 UGDG README UPDATES
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/images/Ui.png
Labels: file.devGuide, file.userGuide, status.readyToMerge, v1.4

#121 v1.4 Update UG
  docs/UserGuide.adoc
Labels: file.userGuide, status.readyToMerge

#124 UserGuide: Add rename command use guide, update prefix for team
  docs/UserGuide.adoc
Labels: file.userGuide

#108 Update team display to reflect remove command, add rename command
  src/main/java/seedu/address/commons/events/ui/RemoveSelectedTeamEvent.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/AssignCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/RemarkCommand.java
  src/main/java/seedu/address/logic/commands/RemoveCommand.java
  src/main/java/seedu/address/logic/commands/RenameCommand.java
  src/main/java/seedu/address/logic/commands/ViewCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/AssignCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/CreateCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/RemarkCommandParser.java
  src/main/java/seedu/address/logic/parser/RemoveCommandParser.java
  src/main/java/seedu/address/logic/parser/RenameCommandParser.java
  src/main/java/seedu/address/logic/parser/ViewCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/Remark.java
  src/main/java/seedu/address/model/team/Team.java
  src/main/java/seedu/address/model/team/TeamName.java
  src/main/java/seedu/address/model/team/UniqueTeamList.java
  src/main/java/seedu/address/model/team/exceptions/DuplicateTeamException.java
  src/main/java/seedu/address/ui/TeamDisplay.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/AssignCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/CreateCommandTest.java
  src/test/java/seedu/address/logic/commands/RemarkCommandTest.java
  src/test/java/seedu/address/logic/commands/RemoveCommandTest.java
  src/test/java/seedu/address/logic/commands/RenameCommandTest.java
  src/test/java/seedu/address/logic/commands/ViewCommandTest.java
  src/test/java/seedu/address/logic/parser/RemarkCommandParserTest.java
  src/test/java/seedu/address/model/UniqueTeamListTest.java
  src/test/java/seedu/address/model/person/RemarkTest.java
  src/test/java/seedu/address/model/team/TeamNameTest.java
  src/test/java/seedu/address/testutil/TypicalTeams.java
Labels: status.readyForReview, type.bug

#120 v1.4 change App name
  build.gradle
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  src/main/java/seedu/address/model/UserPrefs.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/test/data/JsonUserPrefsStorageTest/ExtraValuesUserPref.json
  src/test/data/JsonUserPrefsStorageTest/TypicalUserPref.json
  src/test/java/seedu/address/storage/JsonUserPrefsStorageTest.java
  src/test/java/seedu/address/ui/testutil/GuiTestAssert.java
Labels: file.devGuide, v1.4

#138 v1.5 event handler for remarks
  src/main/java/seedu/address/commons/events/ui/PersonDetailsChangedEvent.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/RemarkCommand.java
  src/main/java/seedu/address/logic/commands/TogglePrivacyCommand.java
  src/main/java/seedu/address/ui/PlayerDetails.java
Labels: status.readyForReview, v1.5

#137 V1.5 change theme
  docs/UserGuide.adoc
  docs/images/Ui.png
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/commons/events/ui/ChangeThemeEvent.java
  src/main/java/seedu/address/logic/commands/ChangeThemeCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/ChangeThemeCommandParser.java
  src/main/java/seedu/address/model/UserPrefs.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/TeamDisplay.java
  src/main/resources/view/LightTheme.css
  src/main/resources/view/MainWindow.fxml
  src/test/java/seedu/address/logic/commands/ChangeThemeCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/ChangeThemeCommandParserTest.java
Labels: status.readyForReview, type.enhancement, v1.5

#160 V1.5 add logo and change default window size
  collated/functional/Codee.md
  collated/functional/jordancjq-reused.md
  collated/functional/jordancjq.md
  collated/functional/lithiumlkid.md
  collated/functional/lohtianwei.md
  collated/test/Codee.md
  collated/test/jordancjq-reused.md
  collated/test/lithiumlkid.md
  collated/test/lohtianwei.md
  docs/images/MyTeamManagerLogo.png
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/resources/images/MyTeamManagerLogo.png
  src/main/resources/view/LightTheme.css
  src/main/resources/view/MainWindow.fxml
Labels: status.readyToMerge, v1.5rc

#162 v1.5 fix bug event handler for edit -> undo
  src/main/java/seedu/address/logic/commands/EditCommand.java
Labels: v1.5rc

#165 V1.5 fix
  README.adoc
  docs/UserGuide.adoc
  docs/diagrams/SetTagCommandSequence.pptx
  docs/diagrams/~$SetTagCommandSequence.pptx
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/ui/PersonListPanel.java
  src/main/java/seedu/address/ui/PlayerDetails.java
  src/test/java/seedu/address/ui/testutil/GuiTestAssert.java
Labels: status.readyForReview, status.readyToMerge, v1.5rc

#168 v1.5rc change sampleDataUtil
  collated/functional/Codee.md
  collated/functional/lohtianwei.md
  docs/diagrams/SetTagCommandSequence.pptx
  docs/diagrams/~$SetTagCommandSequence.pptx
  docs/team/codeeong.adoc
  images/AlexYeoh.png
  images/BerniceYu.png
  images/CharlotteOliveiro.png
  images/placeholder.png
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/ui/PersonListPanel.java
Labels: status.readyForReview

#167 Fix issues: #139, #149, #147
  docs/UserGuide.adoc
  src/main/java/seedu/address/logic/commands/AssignCommand.java
  src/main/java/seedu/address/logic/commands/ViewCommand.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/test/java/seedu/address/logic/commands/AssignCommandTest.java
Labels: status.readyForReview

#171 Lock Unlock Feature
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/KeyCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/KeyCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/UserPrefs.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
Labels: status.readyForReview

#170 Update documentation for v1.5rc
  README.adoc
  collated/functional/jordancjq-reused.md
  collated/functional/jordancjq.md
  collated/test/jordancjq-reused.md
  collated/test/jordancjq.md
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/team/johndoe.adoc
  docs/team/jordanchong.adoc
  src/main/java/seedu/address/logic/commands/RemarkCommand.java
  src/main/java/seedu/address/logic/parser/RemarkCommandParser.java
  src/main/java/seedu/address/model/person/Remark.java
  src/test/java/seedu/address/logic/commands/RemarkCommandTest.java
  src/test/java/seedu/address/logic/parser/RemarkCommandParserTest.java
  src/test/java/seedu/address/model/person/RemarkTest.java
Labels: status.readyForReview

#172 Add ParserTest for View, Assign, Remove, Rename
  src/main/java/seedu/address/logic/parser/RemoveCommandParser.java
  src/main/java/seedu/address/logic/parser/ViewCommandParser.java
  src/main/java/seedu/address/model/team/Team.java
  src/main/java/seedu/address/model/team/TeamName.java
  src/test/java/seedu/address/logic/commands/AssignCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/RenameCommandTest.java
  src/test/java/seedu/address/logic/commands/ViewCommandTest.java
  src/test/java/seedu/address/logic/parser/AssignCommandParserTest.java
  src/test/java/seedu/address/logic/parser/CreateCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/logic/parser/RemoveCommandParserTest.java
  src/test/java/seedu/address/logic/parser/RenameCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ViewCommandParserTest.java
  src/test/java/seedu/address/testutil/TeamBuilder.java
  src/test/java/seedu/address/testutil/TypicalTeams.java
  src/test/java/seedu/address/ui/TeamDisplayTest.java
Labels: status.readyForReview

#178 V1.5rc ppp
  collated/functional/Codee.md
  collated/functional/jordancjq.md
  collated/functional/lohtianwei.md
  collated/test/jordancjq.md
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/diagrams/ChangeThemeCommandSequence.pptx
  docs/diagrams/SetTagCommandSequence.pptx
  docs/images/ChangeThemeCommandDiagram.png
  docs/images/SetTagCommandSequence.png
  docs/team/codeeong.adoc
  images/AaronRamsey.png
  src/main/resources/view/LightTheme.css
Labels: status.readyForReview, status.readyToMerge

#173 UserGuide/PPP: Documentation for v1.5rc
  docs/UserGuide.adoc
  docs/team/jordanchong.adoc
Labels: status.ongoing

#175 Update assign command: unassign when team is not specified
  docs/UserGuide.adoc
  src/main/java/seedu/address/logic/commands/AssignCommand.java
  src/main/java/seedu/address/logic/parser/AssignCommandParser.java
  src/main/java/seedu/address/logic/parser/CreateCommandParser.java
  src/main/java/seedu/address/logic/parser/RenameCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/exceptions/DuplicatePersonException.java
  src/main/java/seedu/address/model/team/TeamName.java
  src/main/java/seedu/address/model/team/UniqueTeamList.java
  src/main/java/seedu/address/model/team/exceptions/TeamNotFoundException.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/AssignCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/AssignCommandParserTest.java
  src/test/java/seedu/address/logic/parser/CreateCommandParserTest.java
  src/test/java/seedu/address/logic/parser/RenameCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ViewCommandParserTest.java
Labels: status.readyForReview, type.enhancement

#179 UserGuide: Documentation for 1.5rc
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
Labels: file.userGuide, status.ongoing

#169 Bug fixes
  docs/UserGuide.adoc
  docs/team/ahmadsyafiq.adoc
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/model/person/Avatar.java
  src/main/java/seedu/address/ui/CommandBox.java
  src/main/java/seedu/address/ui/HelpWindow.java
  src/main/java/seedu/address/ui/MainWindow.java
Labels: status.readyForReview

#196 v1.5 fix bugs in edit and remark command, edited tests
  docs/UserGuide.adoc
  src/main/java/seedu/address/commons/events/ui/PersonDetailsChangedEvent.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/RemarkCommand.java
  src/main/java/seedu/address/logic/commands/TogglePrivacyCommand.java
  src/main/java/seedu/address/ui/PlayerDetails.java
  src/main/resources/view/PlayerDetails.fxml
  src/test/java/guitests/guihandles/PersonListPanelHandle.java
  src/test/java/guitests/guihandles/PlayerDetailsHandle.java
  src/test/java/seedu/address/logic/parser/RemarkCommandParserTest.java
  src/test/java/systemtests/AddressBookSystemTest.java
  src/test/java/systemtests/EditCommandSystemTest.java
Labels: v1.5

#197 [Tests][Documentations]
  docs/DeveloperGuide.adoc
  docs/images/KeyactDiag.png
  docs/images/sortSeq.png
  docs/team/lohtianwei.adoc
  src/main/java/seedu/address/logic/commands/KeyCommand.java
  src/main/java/seedu/address/logic/commands/SortCommand.java
  src/main/java/seedu/address/logic/commands/TogglePrivacyCommand.java
  src/main/java/seedu/address/logic/parser/TogglePrivacyCommandParser.java
  src/main/java/seedu/address/model/person/UniquePersonList.java
  src/test/java/seedu/address/logic/commands/KeyCommandTest.java
  src/test/java/seedu/address/logic/commands/TogglePrivacyCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/TogglePrivacyCommandParserTest.java
  src/test/java/seedu/address/testutil/EditPersonPrivacyBuilder.java
Labels: file.devGuide, status.ongoing

#210 V1.5 dgug
  docs/DeveloperGuide.adoc
  docs/diagrams/ChangeThemeCommandSequence.pptx
  docs/diagrams/HighLevelSequenceDiagrams.pptx
  docs/diagrams/PlayerDetailsDiagram.pptx
  docs/diagrams/SetTagCommandSequence.pptx
  docs/diagrams/ShowNewTeamDiagram.pptx
  docs/images/ChangeThemeCommandDiagram.png
  docs/images/ChangeThemeDiagram.png
  docs/images/DarkTheme.png
  docs/images/LightTheme.png
  docs/images/PlayerDetailsDiagram.png
  docs/images/SetTagCommandDiagram.png
  docs/images/SetTagCommandSequence.png
  docs/images/ShowNewTeamDiagram.png
  src/main/java/seedu/address/logic/commands/RemarkCommand.java
  src/test/java/seedu/address/logic/commands/RemarkCommandTest.java
Labels: status.ongoing
