Repository CS2103JAN2018-F14-B1/main, pull requests merged in 2018-03, with the labels that each got.

#49 AboutUs: Add team member's profile picture
  docs/AboutUs.adoc
  docs/images/codeeo.jpg
  docs/images/ltianwei.jpg
  docs/images/syafiq.jpg
Labels: type.task

#50 Update User Guide
  docs/UserGuide.adoc
Labels: file.userGuide, priority.high, status.ongoing

#53 Update userguide
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
Labels: file.userGuide, priority.high, status.ongoing

#56 Edited userguide features portion 3.4-3.6
  docs/UserGuide.adoc
Labels: file.userGuide, priority.high, status.ongoing

#55 codee - add intro and 3.11-3.15
  docs/UserGuide.adoc
Labels: file.userGuide, priority.high, status.ongoing

#66 V1.1 choose color tag
  src/main/java/seedu/address/logic/commands/SetCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/SetCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/tag/Tag.java
  src/main/java/seedu/address/storage/XmlAdaptedTag.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/DarkTheme.css
  src/test/data/XmlSerializableAddressBookTest/invalidTagAddressBook.xml
  src/test/data/XmlSerializableAddressBookTest/typicalPersonsAddressBook.xml
  src/test/data/XmlUtilTest/invalidPersonField.xml
  src/test/data/XmlUtilTest/missingPersonField.xml
  src/test/data/XmlUtilTest/tempAddressBook.xml
  src/test/data/XmlUtilTest/validPerson.xml
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/SetCommandTest.java
  src/test/java/seedu/address/model/tag/TagTest.java
  src/test/java/seedu/address/ui/testutil/GuiTestAssert.java
Labels: priority.high, status.readyForReview, type.enhancement

#52 Added autocomplete enhancement using a Trie of commands. Added Comman…
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/CommandTrie.java
  src/main/java/seedu/address/logic/commands/TrieNode.java
  src/main/java/seedu/address/ui/CommandBox.java
  src/test/java/seedu/address/logic/AutocompleteTest.java
  src/test/java/seedu/address/ui/CommandBoxTest.java
Labels: priority.high, status.readyForReview, type.enhancement

#54 Enhance add command with optional fields
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/Address.java
  src/main/java/seedu/address/model/person/Phone.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/systemtests/AddCommandSystemTest.java
Labels: priority.high, status.readyForReview, type.enhancement

#58 Implement RemarkCommand
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/RemarkCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/RemarkCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/Remark.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/XmlAdaptedPerson.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/PersonListCard.fxml
  src/test/data/XmlAddressBookStorageTest/invalidAndValidPersonAddressBook.xml
  src/test/data/XmlSerializableAddressBookTest/typicalPersonsAddressBook.xml
  src/test/data/XmlUtilTest/validAddressBook.xml
  src/test/java/guitests/guihandles/PersonCardHandle.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/RemarkCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/RemarkCommandParserTest.java
  src/test/java/seedu/address/model/person/RemarkTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
  src/test/java/seedu/address/ui/testutil/GuiTestAssert.java
Labels: priority.high, status.readyForReview, type.enhancement

#57 Added sort function
  src/main/java/seedu/address/logic/commands/SortCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/SortCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/UniquePersonList.java
  src/main/java/seedu/address/model/person/exceptions/NoPlayerException.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/SortCommandTest.java
  src/test/java/seedu/address/logic/parser/SortCommandParserTest.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: priority.high, status.ongoing, type.enhancement

#81 V1.2 DG - update implementation section
  docs/DeveloperGuide.adoc
Labels: file.devGuide, v1.2

#71 UserGuide: Add new commands and how to use
  docs/UserGuide.adoc
Labels: file.userGuide, priority.medium, status.ongoing, v1.2

#70 DevGuide: Update information and implementation
  docs/DeveloperGuide.adoc
Labels: file.devGuide, priority.medium, status.ongoing, v1.2

#73 DevGuide: Implementations
  docs/DeveloperGuide.adoc
Labels: file.devGuide, priority.medium, status.ongoing, v1.2

#72 UserGuide: Updated userguide for sort commands and added new commands
  docs/UserGuide.adoc
Labels: file.userGuide, priority.medium, status.ongoing, v1.2

#77 Autocomplete v2
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/CommandTrie.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/commands/SelectCommand.java
  src/main/java/seedu/address/ui/CommandBox.java
  src/test/java/seedu/address/ui/CommandBoxTest.java
Labels: status.readyForReview, type.enhancement, v1.2

#74 Add Team Implementation: create command
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/CreateCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/RemarkCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/CreateCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/ReadOnlyAddressBook.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/team/Team.java
  src/main/java/seedu/address/model/team/TeamName.java
  src/main/java/seedu/address/model/team/UniqueTeamList.java
  src/main/java/seedu/address/model/team/exceptions/DuplicateTeamException.java
  src/main/java/seedu/address/model/team/exceptions/TeamNotFoundException.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/XmlAdaptedPerson.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/PersonListCard.fxml
  src/test/data/XmlAddressBookStorageTest/invalidAndValidPersonAddressBook.xml
  src/test/data/XmlSerializableAddressBookTest/typicalPersonsAddressBook.xml
  src/test/data/XmlUtilTest/validAddressBook.xml
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/CreateCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/CreateCommandParserTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/UniqueTeamListTest.java
  src/test/java/seedu/address/model/team/TeamNameTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/TypicalIndexes.java
  src/test/java/seedu/address/testutil/TypicalTeams.java
Labels: status.ongoing, type.enhancement, v1.2

#87 UserGuide: Update for v1.3
  docs/UserGuide.adoc
Labels: file.userGuide, status.ongoing, v1.3

#89 V1.3 change theme of MTM
  src/main/java/seedu/address/commons/core/Config.java
  src/main/java/seedu/address/ui/PlayerDetails.java
  src/main/java/seedu/address/ui/UiManager.java
  src/main/resources/images/football.png
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/PlayerDetails.fxml
  src/test/java/seedu/address/commons/core/ConfigTest.java
Labels: v1.3

#84 Check input for <UNSPECIFIED> and display invalid input
  src/main/java/seedu/address/logic/parser/ParserUtil.java
Labels: type.bug, v1.3

#93 changed date "since june 2016" in UG DG
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
Labels: file.devGuide, file.userGuide, v1.3

#94 Morph/Enhanced person object to have more fields: rating, position, and jersey number
  docs/UserGuide.adoc
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/CommandTrie.java
  src/main/java/seedu/address/logic/commands/CreateCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/commands/RemarkCommand.java
  src/main/java/seedu/address/logic/commands/SetCommand.java
  src/main/java/seedu/address/logic/commands/SortCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/person/JerseyNumber.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/Position.java
  src/main/java/seedu/address/model/person/Rating.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/XmlAdaptedPerson.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/PersonListCard.fxml
  src/test/data/XmlAddressBookStorageTest/invalidAndValidPersonAddressBook.xml
  src/test/data/XmlSerializableAddressBookTest/typicalPersonsAddressBook.xml
  src/test/data/XmlUtilTest/validAddressBook.xml
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/EditPersonDescriptorTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
  src/test/java/seedu/address/ui/CommandBoxTest.java
  src/test/java/systemtests/AddCommandSystemTest.java
Labels: status.readyForReview

#90 Add AssignCommand without test
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/commons/events/model/AddressBookChangedEvent.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/AssignCommand.java
  src/main/java/seedu/address/logic/commands/RemoveCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/AssignCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/RemoveCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/team/Team.java
  src/main/java/seedu/address/model/team/TeamName.java
  src/main/java/seedu/address/model/team/UniqueTeamList.java
  src/main/java/seedu/address/storage/XmlAdaptedTeam.java
  src/main/java/seedu/address/storage/XmlSerializableAddressBook.java
  src/test/java/seedu/address/logic/commands/AddCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/systemtests/AddCommandSystemTest.java
Labels: status.ongoing, type.enhancement, v1.3

#97 changed version number in DG
  src/main/java/seedu/address/MainApp.java
Labels: v1.3

#99 V1.3 README update picture for UI
  docs/images/Ui.png
Labels: status.readyToMerge, v1.3

#88 link team display bar to the logic component and storage
  docs/diagrams/~$UndoRedoSequenceDiagram.pptx
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/team/Team.java
  src/main/java/seedu/address/storage/XmlAdaptedTeam.java
  src/main/java/seedu/address/storage/XmlSerializableAddressBook.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/java/seedu/address/ui/TeamDisplay.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/MainWindow.fxml
  src/test/java/guitests/guihandles/MainWindowHandle.java
  src/test/java/guitests/guihandles/TeamDisplayHandle.java
  src/test/java/seedu/address/commons/util/XmlUtilTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/testutil/TeamBuilder.java
  src/test/java/seedu/address/ui/TeamDisplayTest.java
  src/test/java/seedu/address/ui/testutil/GuiTestAssert.java
Labels: status.readyForReview, status.readyToMerge, v1.3

#95 Add ViewCommand without logic
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  src/main/java/seedu/address/logic/commands/ViewCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/ViewCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
Labels: status.ongoing, type.enhancement, v1.3
